# Generated by Django 3.2.6 on 2022-05-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather_data',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='weather_data',
            name='station_name',
        ),
    ]
