# Generated by Django 3.2.6 on 2022-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20220504_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_data',
            name='loc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='weather_data',
            name='station_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='weather_data',
            name='station_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='weather_data_current',
            name='loc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='tmp_measure_max',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='tmp_measure_min',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='tmp_measure_moy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='wind_measure_max',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='wind_measure_min',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='wind_measure_moy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data_current',
            name='station_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data_current',
            name='station_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data_current',
            name='tmp_measure',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data_current',
            name='wind_measure',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
