# Generated by Django 3.2.6 on 2022-05-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weather_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_data_current',
            name='tmp_measure_max',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='weather_data_current',
            name='tmp_measure_min',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='weather_data_current',
            name='wind_measure_max',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='weather_data_current',
            name='wind_measure_min',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
