# Generated by Django 3.2.6 on 2022-05-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20220505_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_data',
            name='pays',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='weather_data_current',
            name='pays',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
